import Link from "next/link";
import { ArticleSchema } from "@/components/evidence/ArticleSchema";
import { CornerstoneHeader } from "@/components/evidence/CornerstoneHeader";
import { FaqBlock } from "@/components/evidence/FaqBlock";
import { PriceTable } from "@/components/evidence/PriceTable";
import { RelatedTool } from "@/components/evidence/RelatedTool";
import { Sources } from "@/components/evidence/Sources";
import { evidenceRows, observationSourceEntries } from "@/data/content";
import { TECHNICAL_SOURCES } from "@/data/technicalSources";
import { pageMetadata } from "@/lib/seo";

const PATH="/roofing/five-rib";
const DESCRIPTION="Five-rib and trapezoidal roofing NZ guide covering profile names, cover widths, minimum pitch, public material observations and why installation can cost slightly more than corrugate.";
const ids=["lr-17","lr-18"];
export const metadata=pageMetadata({title:"Five-rib roofing NZ — trapezoidal profiles & cost",description:DESCRIPTION,path:PATH});
export default function FiveRibPage(){const sources=[...observationSourceEntries(ids),TECHNICAL_SOURCES.metalcraftFiveRib,TECHNICAL_SOURCES.dimondHiFive,TECHNICAL_SOURCES.buildingE2];return <>
<ArticleSchema headline="Five-rib and trapezoidal roofing in New Zealand" description={DESCRIPTION} path={PATH}/>
<CornerstoneHeader crumbs={[{label:"Home",href:"/"},{label:"Roofing",href:"/roofing"},{label:"Five-rib roofing"}]} eyebrow="Five-rib / trapezoidal" title="Five-rib roofing in NZ: the profiles, cost and installation differences" answer={<><p>“Five-rib” is a useful category name rather than one manufacturer product. Metalcraft MC760/T-Rib and Dimond Hi Five are examples of trapezoidal profiles with five main ribs.</p><p>Material cost is often close to corrugate. RoofHub expects only a <strong>small installed premium</strong> on a comparable simple roof, mainly because cutting and flashing around ribs can require more labour.</p></>} facts={[{label:"Category",value:"Trapezoidal long-run"},{label:"Example cover",value:"~760–765 mm"},{label:"Example min pitch",value:"3° on cited systems"},{label:"Reviewed",value:"26 Sep 2026"}]}/>
<section className="section section--white"><div className="container article-two-col"><div className="article-stack"><p className="eyebrow">What manufacturers call it</p><h2>Different names, same broad profile family</h2><p>Metalcraft describes MC760 as a five-rib trapezoidal profile with 760 mm cover and a stated 3° minimum pitch. Dimond's Hi Five also uses five ribs and publishes a nominal cover around 765 mm with a 3° minimum pitch.</p><p>This is why RoofHub groups several manufacturer names under “five-rib / trapezoidal” for pricing, while still linking back to the exact product specification.</p></div><RelatedTool title="Estimate a five-rib roof" href="/tools/detailed-roof-estimator" copy="Select five-rib / trapezoidal and reuse your measured roof quantities."/></div></section>
<section className="section section--sage"><div className="container article-stack"><div><p className="eyebrow">Public material observations</p><h2>Five-rib supply pricing is less transparent than the technical data</h2><p>RoofHub currently has fewer directly comparable five-rib retail observations than corrugate. That is a data-quality limitation worth showing, not hiding.</p></div><PriceTable caption="Five-rib material observations" rows={evidenceRows(ids)}/><div className="evidence-callout"><strong>RoofHub pricing approach:</strong> corrugate and five-rib material bands remain close. The estimator's five-rib labour range is slightly wider because manual notching around some ridge, hip and valley details can add time.</div></div></section>
<section className="section section--white"><div className="container article-stack"><div><p className="eyebrow">Low-pitch use</p><h2>Five-rib profiles can work at lower pitches than conventional corrugate</h2></div><p>The cited MC760 and Hi Five systems publish minimum pitches of 3°, compared with 8° for the cited corrugate systems. That does not make every five-rib profile interchangeable: sheet length, run-off, fixing, wind zone and manufacturer details still matter.</p><p>See <Link className="text-link" href="/guides/roof-pitch">roof pitch and area</Link> for the geometry side.</p></div></section>
<section className="section"><div className="container article-stack"><div><p className="eyebrow">Sources</p><h2>Sources and manufacturer references</h2></div><Sources sources={sources}/></div></section>
<section className="section section--sage"><div className="container faq-layout"><div><p className="eyebrow">FAQ</p><h2>Five-rib roofing questions</h2></div><FaqBlock faqs={[{q:"Is five-rib roofing more expensive than corrugate?",a:"Usually only slightly in RoofHub's working model for a comparable roof. Material pricing can be close; the small difference is mainly an allowance for more involved profile cutting and flashing details."},{q:"Is five-rib the same product from every manufacturer?",a:"No. It is a category description. Rib dimensions, cover, thicknesses, fixing requirements and product names vary, so use the exact manufacturer specification for the selected profile."},{q:"Can five-rib roofing go on a lower pitch than corrugate?",a:"Some NZ five-rib/trapezoidal systems can. The cited Metalcraft MC760 and Dimond Hi Five systems state 3° minimum pitch, while the cited corrugate systems state 8°. Exact project requirements still need checking."}]} /></div></section>
</>}
