import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "How to prepare for a roofing quote" };

export default function GuidePage() {
  return <>
    <section className="article-hero"><div className="container article-shell"><div><p className="breadcrumbs"><Link href="/guides">Guides</Link> / Project planning</p><p className="eyebrow">Representative draft guide · 5 min read</p><h1>How to prepare for a roofing quote</h1><p className="article-lede">A useful quote starts with a clear description of the project. You do not need to know every technical detail, but a little preparation makes it easier to compare scope, assumptions and exclusions.</p></div></div></section>
    <section className="article-section"><div className="container article-layout"><article className="prose"><div className="answer-box"><strong>Quick answer</strong><p>Gather the property location, what you know about the existing roof, a few useful photos, any plans or measurements you already have, and the outcome you are trying to achieve. Then compare quotes on scope as well as price.</p></div><h2>1. Start with the problem, not the product</h2><p>Instead of deciding in advance that you need a particular roofing product, describe what is happening: age, leaks, visible corrosion, broken tiles, planned renovation, insurance work, or a roof that simply appears to be reaching the end of its serviceable life.</p><p className="draft-callout"><strong>Draft-content note:</strong> final technical guidance will be reviewed against appropriate NZ sources before indexing is enabled.</p><h2>2. Give the roofer enough context to prepare properly</h2><p>Useful information can include the address or town, approximate building type, known roof material, number of storeys, access constraints, existing solar or penetrations, and photos from safe ground-level positions.</p><h2>3. Compare what is included — not only the bottom-line price</h2><p>Two quotes can look similar while covering different work. RoofHub's future quote-checking content should help users identify differences in removal, disposal, scaffold, flashings, underlay, gutters, penetrations, insulation interfaces and other scope items where relevant.</p><h2>4. Keep unknowns visible</h2><p>A quote prepared before a detailed inspection may reasonably contain assumptions. The important thing is that those assumptions are visible rather than hidden.</p><h2>5. Ask what happens next</h2><p>Clarify how the contractor handles variations, weather delays, access, warranties, site protection and any project-specific approvals or specialist requirements.</p><div className="article-end-cta"><h2>Eventually, RoofHub can do some of this preparation for you.</h2><p>Measurements, photos, pricing context and unanswered questions can flow into one project summary rather than being retyped into every enquiry.</p><Link className="button button--primary" href="/tools">See the tool plan</Link></div></article><aside className="article-sidebar"><div className="toc-card"><strong>On this page</strong><a href="#">Start with the problem</a><a href="#">Project context</a><a href="#">Compare scope</a><a href="#">Keep unknowns visible</a></div><div className="method-card"><span>Methodology</span><p>This v0.1 article is representative design content, not final published NZ roofing guidance.</p></div></aside></div></section>
  </>;
}
