import Link from "next/link";
import { ArticleSchema } from "@/components/evidence/ArticleSchema";
import { TECHNICAL_SOURCES } from "@/data/technicalSources";
import { Sources } from "@/components/evidence/Sources";
import { pageMetadata } from "@/lib/seo";

const PATH="/guides/how-to-prepare-for-a-roofing-quote";
const DESCRIPTION="What to gather, what to ask and how to compare New Zealand roofing quotes on scope, assumptions, access, removal and exclusions — not only the bottom-line price.";
export const metadata=pageMetadata({title:"How to prepare for a roofing quote",description:DESCRIPTION,path:PATH});

export default function GuidePage(){return <>
<ArticleSchema headline="How to prepare for a roofing quote" description={DESCRIPTION} path={PATH}/>
<section className="article-hero"><div className="container article-shell"><p className="breadcrumbs"><Link href="/guides">Guides</Link><span>/</span> Project planning</p><p className="eyebrow">Project planning · 5 min read</p><h1>How to prepare for a roofing quote</h1><p className="article-lede">A useful quote starts with a clear project description. You do not need to become a roofer first — but a little preparation makes it much easier to compare scope, assumptions and exclusions.</p><div className="article-meta"><span>New Zealand</span><span>Scope-first comparison</span><span>Reviewed 26 Sep 2026</span></div></div></section>
<section className="article-section"><div className="container article-layout"><article className="prose">
<div className="answer-box"><strong>Quick answer</strong><p>Gather the property location, what you know about the existing roof, useful ground-level photos, any plans or measurements you already have, and the outcome you want. Then compare quotes on what is included — removal, scaffold, flashings, underlay, repairs and GST — not only the final number.</p></div>
<h2 id="problem">1. Start with the problem, not the product</h2><p>Describe what is happening: roof age if known, leaks, visible corrosion, damaged tiles, a planned extension, insurance work, or simply that the roof appears to be reaching the end of its serviceable life. The contractor can then assess whether the likely solution is repair, partial work or replacement.</p>
<h2 id="context">2. Give enough context for the site visit</h2><p>Useful information includes the suburb/town, building type, known roof material, number of storeys, approximate roof area, access constraints, existing solar/skylights/chimneys and photos taken safely from ground level. Plans are useful when available.</p><div className="article-check-grid"><div><strong>Useful to have</strong><ul><li>Property location</li><li>Roof type if known</li><li>Approximate area or plans</li><li>Safe ground-level photos</li></ul></div><div><strong>Useful to explain</strong><ul><li>Leaks or visible damage</li><li>Timing constraints</li><li>Access / hillside issues</li><li>Renovation context</li></ul></div></div>
<h2 id="scope">3. Compare the scope, not just the bottom line</h2><p>Two totals can differ because one includes work the other leaves out. Check whether the quote includes removal and disposal, scaffold or edge protection, underlay, flashings, fixings, gutters/downpipes, penetrations, freight and GST.</p><p>For reroofing, RoofHub's <Link className="text-link" href="/pricing/reroof-cost">re-roof cost guide</Link> shows why removal and access should remain separate cost layers.</p>
<h2 id="unknowns">4. Keep unknowns visible</h2><p>Some issues cannot be confirmed before strip-off — rotten timber, hidden substrate damage or asbestos risk are common examples. A good quote or estimate should say how those unknowns will be handled rather than silently assuming they cost nothing.</p>
<h2 id="asbestos">5. Identify older roofing risks before disturbing them</h2><p>WorkSafe lists roofing products such as Decramastic tiles among materials roofers may encounter with asbestos. If an older roof may contain asbestos, assessment/testing can be required before normal removal work proceeds.</p>
<h2 id="next">6. Ask what happens if the scope changes</h2><p>Clarify how variations are approved, how weather delays are handled, what warranties apply, how the site is protected, and whether specialist work or additional approvals may be needed.</p>
<div className="article-end-cta"><p className="eyebrow">Bring measurements if you have them</p><h2>Turn the project into a structured estimate.</h2><p>Use actual measurements or trace a plan, then keep the selected roof system, removal scope and access assumptions in one project.</p><Link className="button button--primary" href="/tools/detailed-roof-estimator">Open detailed estimator</Link></div>
<h2 id="sources">Source</h2><Sources sources={[TECHNICAL_SOURCES.worksafeAsbestos]}/>
</article><aside className="article-sidebar"><nav className="toc-card" aria-label="On this page"><strong>On this page</strong><a href="#problem">Start with the problem</a><a href="#context">Project context</a><a href="#scope">Compare scope</a><a href="#unknowns">Keep unknowns visible</a><a href="#asbestos">Older roofing risks</a><a href="#next">Variations and next steps</a></nav><div className="method-card"><span>RoofHub method</span><p>Useful information first. A preliminary estimate is kept separate from an inspected contractor quote.</p></div></aside></div></section>
</>}
