import Link from "next/link";
import { ArrowRight, Check } from "@/components/Icons";
import { pageMetadata } from "@/lib/seo";

export const metadata=pageMetadata({title:"About RoofHub",description:"RoofHub is an independent New Zealand roofing information, pricing and calculation platform built around traceable evidence and useful tools.",path:"/about"});
const principles=[
  ["01","Useful before an enquiry","Pricing, guides and tools deliver value before RoofHub asks for contact details."],
  ["02","Evidence stays attached","Important price observations keep their source, date, units, GST status and scope."],
  ["03","Tools share the same logic","Measurement and pricing inputs are designed to flow through one roofing data model."],
  ["04","Uncertainty stays visible","A preliminary estimate is labelled as an estimate, not dressed up as a quote."]
] as const;
export default function AboutPage(){return <>
<section className="page-intro page-intro--sage"><div className="container page-intro__grid"><div><p className="eyebrow">About RoofHub</p><h1>An independent NZ roofing knowledge and calculation platform.</h1></div><div className="page-intro__aside"><p>RoofHub turns fragmented roofing prices, technical specifications and project information into source-backed guides, comparisons and tools that homeowners and roofing professionals can actually use.</p></div></div></section>
<section className="section section--white"><div className="container about-grid"><div><p className="eyebrow">Why it exists</p><h2>Roofing information is useful only when the context survives the summary.</h2><p>A supplier may publish sheet pricing. A manufacturer publishes technical limits. A roofer publishes a project example. A regulator publishes safety or compliance guidance. RoofHub's job is to connect those pieces without pretending they are interchangeable.</p></div><ul className="check-list check-list--large"><li><Check/> NZ-specific pricing and terminology</li><li><Check/> Manufacturer-backed technical references</li><li><Check/> Published market observations with provenance</li><li><Check/> Measurement and estimating tools</li><li><Check/> Optional route to a proper site quote</li></ul></div></section>
<section className="section"><div className="container"><div className="principle-grid">{principles.map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
<section className="section section--sage"><div className="container feature-split"><div className="feature-copy"><p className="eyebrow">Commercial model</p><h2>Useful information and lead generation can coexist without confusing the two.</h2><p>RoofHub can help someone understand a roof even if they never submit an enquiry. If they do want a formal quote, the measurements and project context they choose to share can make that enquiry more useful to both sides.</p></div><div className="evidence-callout"><strong>Editorial independence:</strong> a provider relationship does not buy a favourable comparison or change how a technical source is represented. Pricing methodology is documented separately.</div></div></section>
<section className="section section--dark"><div className="container cta-band cta-band--dark"><div><p className="eyebrow">See the method</p><h2>How RoofHub turns sources into ranges.</h2><p>The methodology explains the evidence tiers, pricing bases, GST treatment and review process behind the data-driven pages.</p></div><Link className="button button--primary button--large" href="/methodology">Read the methodology <ArrowRight/></Link></div></section>
</>}
