import Link from 'next/link';
import { pageMetadata } from '@/lib/seo';
import { OBSERVATIONS } from '@/data/observations';
import { ARTICLES, articleSourceIds, articleObservationIds, getSource } from '@/data/research';
import { Sources, type SourceEntry } from '@/components/evidence/Sources';
export const metadata = pageMetadata({title:'Roofing sources, evidence and corrections',description:'Check the manufacturers, contractors and technical sources behind RoofHub answers, and understand what was reviewed, what is historical and what remains unknown.',path:'/sources'});
export default function SourcesPage(){
  const sourceIds = [...new Set(Object.values(ARTICLES).flatMap(articleSourceIds))];
  const priceIds = new Set(Object.values(ARTICLES).flatMap(articleObservationIds));
  const sources = new Map<string, SourceEntry>();
  for(const id of sourceIds){const s=getSource(id);sources.set(s.url,{name:`${s.publisher}: ${s.title}`,url:s.url,type:s.kind,tier:['government','manufacturer','industry-technical'].includes(s.kind)?'primary':s.kind==='designer'?'editorial':'market',date:s.publishedAt??undefined,note:[s.note,`Page checked ${s.reviewedAt}.`].filter(Boolean).join(' ')});}
  for(const o of OBSERVATIONS.filter(o=>priceIds.has(o.id))){if(!sources.has(o.sourceUrl))sources.set(o.sourceUrl,{name:o.sourceName,url:o.sourceUrl,type:o.sourceType,tier:o.evidenceTier,date:o.sourceDate,note:`${o.priceContext==='historical-guide'?'Historical price guide. ':''}Source checked ${o.lastCheckedAt??'in the earlier research pass'}. GST ${o.gstBasis==='unknown'?'not stated':o.gstBasis==='incl'?'included':'excluded'}.`});}
  return <>
  <section className="page-intro page-intro--sage"><div className="container page-intro__grid"><div><p className="eyebrow">Evidence & corrections</p><h1>Check the source behind the answer.</h1></div><div className="page-intro__aside"><p>RoofHub links claims to product documents, technical guidance and published business accounts. A checked source is not an endorsement, a site inspection or independent proof of every statement on that website.</p></div></div></section>
  <section className="section section--white"><div className="container article-two-col"><div className="article-stack"><h2>Different evidence answers different questions.</h2><p>Manufacturer specifications support product comparisons. WorkSafe and MBIE support safety and consent context. Contractor accounts illustrate scope and experience. Published prices need their original date, unit, GST and inclusions to remain useful.</p><div className="rh-article-note"><p>We do not republish contractor photography without permission. Project cards link to the original accounts and images. Missing prices, areas and inspection results stay unknown.</p></div></div><div className="article-stack"><h2>What has been reviewed?</h2><p>The current answer collection links to {sources.size} source pages and uses {priceIds.size} distinct pricing observations. Several observations may come from one publisher; this is not a statistically representative market survey.</p><p>The wider research register holds {OBSERVATIONS.length} price observations, including legacy and research-only material. A record existing in that register does not make it eligible for a current price range.</p><Link className="button button--secondary" href="/methodology">Read the evidence method</Link></div></div></section>
  <section className="section section--sage"><div className="container article-stack"><h2>Sources used in the current answer collection</h2><p>Reviewed 28 September 2026. Publication dates remain separate from the date we checked a page.</p><Sources sources={[...sources.values()].sort((a,b)=>a.name.localeCompare(b.name))}/></div></section>
  <section className="section section--white"><div className="container cta-band"><div><h2>Found a better source or a mistake?</h2><p>Send the affected page and the evidence that needs checking. Corrections to prices, dimensions or product status are reviewed in context.</p></div><Link className="button button--primary" href="/contact?topic=Report%20a%20correction">Report a correction</Link></div></section>
  </>;
}
