import Link from "next/link";
import { ArrowRight, Check } from "@/components/Icons";
import { SectionHeading } from "@/components/SectionHeading";
import { pageMetadata } from "@/lib/seo";

export const metadata=pageMetadata({title:"RoofHub pricing methodology",description:"How RoofHub records NZ roofing price observations, keeps pricing bases separate, derives ranges and distinguishes estimates from formal quotes.",path:"/methodology"});
const evidenceTiers=[
  {rank:"Tier 1",title:"Primary evidence",copy:"New Zealand government/regulators, technical bodies, manufacturers, direct supplier listings and product documentation."},
  {rank:"Tier 2",title:"Market evidence",copy:"Published contractor/scaffolder pricing, case studies, merchant listings and public project examples."},
  {rank:"Tier 3",title:"Editorial evidence",copy:"Explanatory articles and experience-based commentary. Useful context, but not treated as independent technical proof."}
];
const provenance=["Publisher and canonical source URL","Source publication/update date where visible","RoofHub observation date","Unit and price basis","GST treatment if stated","Region, inclusions and exclusions","Evidence tier, confidence and review status"];
const pipeline=[
  {n:"01",t:"Record the observation",c:"Raw figures are stored centrally with their source context rather than copied into multiple pages."},
  {n:"02",t:"Normalise the meaning",c:"Material-only, labour-only, supply/install and complete-project observations remain distinct. Units and GST treatment are explicit."},
  {n:"03",t:"Compare like with like",c:"RoofHub uses comparable observations to support indicative ranges and shows broader market spans separately when scopes differ."},
  {n:"04",t:"Review and date",c:"Pricing pages carry a review date. Volatile observations can be marked stale without deleting their provenance."}
];
export default function MethodologyPage(){return <>
<section className="page-intro page-intro--sage"><div className="container page-intro__grid"><div><p className="eyebrow">Methodology</p><h1>How RoofHub roofing data is built.</h1></div><div className="page-intro__aside"><p>RoofHub publishes research and planning estimates, not binding quotes. The useful part is not only the number — it is knowing where the number came from and what it includes.</p></div></div></section>
<section className="section section--white"><div className="container"><div className="three-col"><article className="info-card"><span>01</span><h3>Price bases stay separate</h3><p>Material-only, labour, supply/install and complete reroof figures are never silently blended.</p></article><article className="info-card"><span>02</span><h3>Unknown GST stays unknown</h3><p>An individual source can still be shown with “GST not stated”, but it does not feed a normalised GST-specific RoofHub range.</p></article><article className="info-card"><span>03</span><h3>Estimate ≠ quote</h3><p>Tools support planning. Site conditions and product details still need a contractor to confirm the final scope.</p></article></div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Evidence policy" title="Three evidence tiers, chosen for the claim being made." copy={<p>Ten pages repeating one claim are not ten independent sources. Technical claims favour primary evidence; real-world pricing benefits from market evidence.</p>}/><div className="principle-grid">{evidenceTiers.map(t=><article key={t.rank}><span>{t.rank}</span><h3>{t.title}</h3><p>{t.copy}</p></article>)}</div></div></section>
<section className="section section--sage"><div className="container feature-split"><div className="feature-copy"><p className="eyebrow">Provenance</p><h2>What RoofHub keeps for important observations.</h2><p>Enough context is stored to re-check a number later and to understand why two apparently similar prices should not be averaged together.</p></div><ul className="check-list check-list--large">{provenance.map(x=><li key={x}><Check/> {x}</li>)}</ul></div></section>
<section className="section section--white"><div className="container"><SectionHeading eyebrow="From source to answer" title="One reviewable pipeline."/><ol className="process-stack process-stack--numbered">{pipeline.map(s=><li key={s.n}><span>{s.n}</span><div><strong>{s.t}</strong><p>{s.c}</p></div></li>)}</ol></div></section>
<section className="section"><div className="container narrow"><p className="eyebrow">Range design</p><h2>Observed market span and RoofHub indicative range are not automatically the same thing.</h2><p>A single unusual project can widen the raw observed span dramatically. RoofHub therefore preserves the full observations but only publishes a narrower “indicative” range when there is enough comparable evidence and a documented method for deriving it. Until then, pages show the observations themselves instead of manufacturing precision.</p><p>Corrections and stronger public sources can be submitted through the <Link className="text-link" href="/contact">contact &amp; corrections form</Link>.</p></div></section>
<section className="section section--dark"><div className="container cta-band cta-band--dark"><div><p className="eyebrow">Source catalogue</p><h2>See the types of evidence RoofHub records.</h2><p>The public sources page explains the source policy and how pricing observations are handled.</p></div><Link className="button button--primary button--large" href="/sources">View sources policy <ArrowRight/></Link></div></section>
</>}
