import Link from "next/link";
import { ArticleSchema } from "@/components/evidence/ArticleSchema";
import { CornerstoneHeader } from "@/components/evidence/CornerstoneHeader";
import { FaqBlock } from "@/components/evidence/FaqBlock";
import { PriceTable } from "@/components/evidence/PriceTable";
import { RelatedTool } from "@/components/evidence/RelatedTool";
import { Sources } from "@/components/evidence/Sources";
import { WorkedExample } from "@/components/evidence/WorkedExample";
import { evidenceRows, observationSourceEntries } from "@/data/content";
import { TECHNICAL_SOURCES } from "@/data/technicalSources";
import { pageMetadata } from "@/lib/seo";

const PATH="/roofing/corrugated";
const DESCRIPTION="Corrugated roofing NZ guide: profile dimensions, minimum pitch, public material and complete-reroof pricing observations, installation considerations and calculator.";
const ids=["lr-12","lr-18","lr-07","rr-01","rr-02"];
export const metadata=pageMetadata({title:"Corrugated roofing NZ — prices, pitch & profiles",description:DESCRIPTION,path:PATH});
export default function CorrugatedPage(){const sources=[...observationSourceEntries(ids),TECHNICAL_SOURCES.metalcraftCorrugate,TECHNICAL_SOURCES.steelTubeCustomOrb,TECHNICAL_SOURCES.buildingE2];return <>
<ArticleSchema headline="Corrugated roofing in New Zealand" description={DESCRIPTION} path={PATH}/>
<CornerstoneHeader crumbs={[{label:"Home",href:"/"},{label:"Roofing",href:"/roofing"},{label:"Corrugated roofing"}]} eyebrow="Corrugated long-run" title="Corrugated roofing in NZ: cost, pitch and what changes the price" answer={<><p>Corrugated long-run is the simplest of RoofHub's mainstream metal roof categories. Manufacturers commonly publish an effective cover around <strong>760–762 mm</strong>, and major NZ systems specify a minimum roof pitch of about <strong>8°</strong>.</p><p>Public material listings can be much lower than complete installed reroof rates because labour, removal, flashings and scaffold are separate cost layers.</p></>} facts={[{label:"Profile",value:"Rounded corrugate"},{label:"Typical cover",value:"~760–762 mm"},{label:"Published min pitch",value:"8° on cited systems"},{label:"Reviewed",value:"26 Sep 2026"}]}/>
<section className="section section--white"><div className="container article-stack"><div><p className="eyebrow">Pricing evidence</p><h2>Published corrugated roofing prices</h2></div><PriceTable caption="Corrugated roofing price observations" rows={evidenceRows(ids)}/><p className="source-note">The material listings and complete-project rates above are intentionally not merged. They represent different scopes.</p></div></section>
<section className="section section--sage"><div className="container article-two-col"><div className="article-stack"><p className="eyebrow">Specification</p><h2>Two common manufacturer references</h2><p>Metalcraft publishes Corrugate at <strong>760 mm cover</strong>, <strong>851 mm sheet width</strong> and <strong>8° minimum pitch</strong>. Steel &amp; Tube's Custom Orb technical information also states an <strong>8° minimum pitch</strong> and an effective cover around <strong>762 mm</strong>.</p><p>Exact thickness, coating, wind-zone fixing and run-off requirements belong to the selected product specification, not a generic corrugate rule.</p></div><RelatedTool title="Estimate a corrugated roof" href="/tools/detailed-roof-estimator" copy="Use actual or plan measurements, then select corrugated long-run as the roof system."/></div></section>
<section className="section section--white"><div className="container article-stack"><WorkedExample title="Converting a lineal-metre material price to covered m²" lines={[{label:"Example public material rate",value:"$22.15/lm incl GST"},{label:"Illustrative cover",value:"0.760 m"},{label:"Calculation",value:"$22.15 ÷ 0.760"},{label:"Approx. sheet price per covered m²",value:"$29.14/m² incl GST",highlight:true}]} note="This converts one Bunnings lineal-metre observation using a 760 mm manufacturer cover for illustration. It does not include waste, freight, fixings, underlay, flashings or installation."/><div className="evidence-callout"><strong>Installation difference:</strong> corrugate is generally RoofHub's baseline long-run labour category. Five-rib material can be similarly priced, but some five-rib hip/ridge/valley details require more profile notching.</div></div></section>
<section className="section"><div className="container article-stack"><div><p className="eyebrow">Sources</p><h2>Sources and technical references</h2></div><Sources sources={sources}/></div></section>
<section className="section section--sage"><div className="container faq-layout"><div><p className="eyebrow">FAQ</p><h2>Corrugated roofing questions</h2></div><FaqBlock faqs={[{q:"What pitch does corrugated roofing need?",a:"The cited Metalcraft Corrugate and Steel & Tube Custom Orb systems state an 8° minimum pitch, subject to their detailed design requirements. Do not apply that number to every corrugated product without checking the manufacturer."},{q:"How wide is corrugated roofing?",a:"The total sheet width is wider than the effective cover because sheets overlap. The cited NZ systems have effective cover around 760–762 mm."},{q:"Is a supplier price per lineal metre the same as cost per square metre?",a:"No. Divide the lineal-metre price by the effective cover width in metres to estimate sheet cost per covered m², then separately allow for waste and the rest of the roofing scope."}]} /></div></section>
</>}
